# Hardware acceleration via VA-API (Intel)
hwdec=auto
vo=gpu
#gpu-api=opengl
# gpu-context=waylandvk

# Video quality
#profile=gpu-hq
#scale=ewa_lanczossharp
#cscale=ewa_lanczossharp
#dscale=mitchell

# OSD
osd-font="Noto Sans"
osd-font-size=28

# Screenshot
screenshot-format=png
screenshot-directory=~/Pictures/Screenshots

# Frame Interpolation Settings
video-sync=display-resample
interpolation=yes
tscale=oversample
