color0 #1c1f21
color1 #fd4663
color2 #d0d7dc
color3 #d1d5db
color4 #d2d3da
color5 #b6c1c9
color6 #b7bec7
color7 #f2f2f3
color8 #646a6e
color9 #fd4663
color10 #d0d7dc
color11 #d1d5db
color12 #d2d3da
color13 #b6c1c9
color14 #b7bec7
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #1c1f21
background            #1c1f21
foreground            #f2f2f3
selection_foreground  #b0b3b5
selection_background  #262a2c
active_border_color   #d0d7dc
inactive_border_color #262a2c
url_color             #d0d7dc

active_tab_foreground   #1c1f22
active_tab_background   #d0d7dc
inactive_tab_foreground #b0b3b5
inactive_tab_background #262a2c
cursor_trail_color      #b0b3b5
